# Generated by Django 3.2.16 on 2022-11-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
