# Generated by Django 3.2.16 on 2022-11-29 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, default='default_poll', max_length=200, null=True, upload_to='vote_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='question',
            name='poll_description',
            field=models.CharField(default='0', max_length=200, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='question',
            name='post_description',
            field=models.CharField(default='0', max_length=200, verbose_name='Краткое описание'),
        ),
    ]
